# Assignment 1

# Task 1.1: Environmental Sensor Analytics

In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
raw_temperatures = np.random.normal(loc=24.0, scale=3.0, size=72)

In [4]:
# Simulated corrupt readings
raw_temperatures[[5, 12, 28, 45, 60]] = [99.9, -15.0, 88.8, -50.0, 102.4]
print(raw_temperatures)

[ 25.49014246  23.5852071   25.94306561  28.56908957  23.29753988
  99.9         28.73763845  26.30230419  22.59157684  25.62768013
  22.60974692  22.60281074 -15.          18.26015927  18.8252465
  22.31313741  20.96150664  24.942742    21.27592777  19.7630889
  28.39694631  23.3226711   24.20258461  19.72575544  22.36685183
  24.33276777  20.54701927  25.12709406  88.8         23.12491875
  22.19488016  29.55683455  23.95950833  20.82686721  26.46763474
  20.33746905  24.62659079  18.12098963  20.01544185  24.59058371
  26.21539974  24.51410484  23.65305515  23.09668891  19.56443403
 -50.          22.61808369  27.17136668  25.03085487  18.71087953
  24.97225191  22.84475316  21.969234    25.83502887  27.09299857
  26.79384036  21.48234743  23.07236287  24.99379029  26.92663538
 102.4         23.44302307  20.68099508  20.41138013  26.43757747
  28.06872009  23.78396964  27.01059869  25.08490808  22.06464074
  25.08418682  28.6141097 ]


In [5]:
#create boolean mask
mask = (raw_temperatures >= 15.0) & (raw_temperatures <= 40.0)
print(mask)

[ True  True  True  True  True False  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True]


In [7]:
# Replace invalid values with median of valid temperature
median_temp = np.median(raw_temperatures[mask])
raw_temperatures[~mask] = median_temp
print(raw_temperatures)

[25.49014246 23.5852071  25.94306561 28.56908957 23.29753988 23.65305515
 28.73763845 26.30230419 22.59157684 25.62768013 22.60974692 22.60281074
 23.65305515 18.26015927 18.8252465  22.31313741 20.96150664 24.942742
 21.27592777 19.7630889  28.39694631 23.3226711  24.20258461 19.72575544
 22.36685183 24.33276777 20.54701927 25.12709406 23.65305515 23.12491875
 22.19488016 29.55683455 23.95950833 20.82686721 26.46763474 20.33746905
 24.62659079 18.12098963 20.01544185 24.59058371 26.21539974 24.51410484
 23.65305515 23.09668891 19.56443403 23.65305515 22.61808369 27.17136668
 25.03085487 18.71087953 24.97225191 22.84475316 21.969234   25.83502887
 27.09299857 26.79384036 21.48234743 23.07236287 24.99379029 26.92663538
 23.65305515 23.44302307 20.68099508 20.41138013 26.43757747 28.06872009
 23.78396964 27.01059869 25.08490808 22.06464074 25.08418682 28.6141097 ]


In [9]:
# Statistics
mean = np.mean(raw_temperatures)
std = np.std(raw_temperatures)
variance = np.var(raw_temperatures)

In [10]:
# Print results
print("Mean:", round(mean, 2))
print("Standard Deviation:", round(std, 2))
print("Variance:", round(variance, 2))

Mean: 23.74
Standard Deviation: 2.69
Variance: 7.24


# Task 1.2: Matrix Slicing & Strided Operations

In [11]:
grid = np.arange(10,74).reshape(8,8)  #generate matrix
print(grid)

[[10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57]
 [58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73]]


In [12]:
print(grid[2:6,2:6])   #extract the center 4 × 4 portion of the matrix

[[28 29 30 31]
 [36 37 38 39]
 [44 45 46 47]
 [52 53 54 55]]


In [13]:
print(grid[:,-1])      #extract the last column using a single slicing statement

[17 25 33 41 49 57 65 73]


In [14]:
#4 × 4 downsampled matrix by selecting every second row and every second column.
print(grid[0:8:2,0:8:2])

[[10 12 14 16]
 [26 28 30 32]
 [42 44 46 48]
 [58 60 62 64]]


# Part 2: Sliding Median Filter

In [18]:
#create original noisy signal
signal = np.array([10, 11, 99, 12, 13, -45, 14, 15, 16])
print(f"Original Signal: {signal}")

Original Signal: [ 10  11  99  12  13 -45  14  15  16]


In [19]:
#make a copy to store filter values
filtered_signal = signal.copy()
print(f"Filtered Signal:{filtered_signal}")

Filtered Signal:[ 10  11  99  12  13 -45  14  15  16]


In [20]:
# Apply a sliding median filter using a window of size 3
for i in range(1,len(signal)-1):
    filtered_signal[i] = np.median(signal[i-1:i+2])

print("Original Signal:", signal)
print("Filtered Signal:", filtered_signal)

Original Signal: [ 10  11  99  12  13 -45  14  15  16]
Filtered Signal: [10 11 12 13 12 13 14 15 16]


# How the median filter removes the spikes (99 and -45)

# Why it performs better than using the mean for this type of noise