In [5]:
import numpy as np
a = np.ones((3,3))
b = np.array([1,2,3])    # B is stretched to (3,3) automatically

In [6]:
c = a + b
print(c)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [8]:
d = np.array([1,2,3]).reshape(3,1)    #transpose
e = np.array([1,2,3])
f = d + e
print(f)  #Creates a 3*3 grid

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [10]:
p = np.array([2,4,6,8])
print(p.reshape(2,2))

[[2 4]
 [6 8]]


# Random Numbers

In [15]:
print(np.random.randint(7))   #one random int num

6


In [16]:
print(np.random.randn(10))     #random +ve -ve 10 numbers

[-0.51942921 -0.88976647  0.66953207 -0.6968099   0.69215566 -1.06921423
 -0.20914374 -1.24122665 -0.26179458 -1.58317273]


In [17]:
print (np.random.rand(3,3))      #random 3*3 matrix 

[[0.45342835 0.95659226 0.24509586]
 [0.6932923  0.3420253  0.8769166 ]
 [0.50385604 0.55451496 0.8123585 ]]


# Boolean Masking

In [22]:
data = np.random.randn(100)
print(data)

[-0.21627865 -0.34154221 -3.53425247  0.46562391 -0.856914    1.72825685
  0.29749616  0.89102853 -0.35228651 -0.02562706 -0.53914427  0.61549622
 -2.30669643 -1.4540945  -0.42548776  0.35304402 -0.91452006  0.81112565
  1.02887973 -0.07406563  2.32285177  2.38624074 -1.01698703 -0.18096967
 -0.26272308 -0.87211172  1.05998761  2.2847969   0.53804723  0.59377332
 -1.07383575  1.18148919 -0.2078987   0.22865404 -0.94536526  1.56080307
 -0.50007996  0.00687868 -1.02932949 -1.27834672 -0.4441492   1.40684332
  1.53917332  0.35073054  0.15271152 -1.7005202   1.45798452  1.16482599
 -0.1445758   0.70628595  0.13014745  0.12411428 -0.80988736 -0.16583979
 -0.43599011  1.22622491 -0.51606453  1.61652508 -0.28430603 -1.76677603
  0.37596724 -1.21316196  1.3288511   0.54390308  0.42551651 -0.89147277
 -0.14912283  1.05158529 -0.34991279  0.52644379 -0.08288773  1.78149978
 -0.87902369  1.04022978 -0.57557692 -1.3791811   1.18068501 -0.41646497
  1.56736404  0.59720237 -1.70323511 -0.35194731 -1

In [23]:
data = np.random.randn(100)
mask = data > 0
pos_data = data[mask]

In [24]:
print(pos_data)

[1.62240213 1.10167831 0.19043129 0.75215737 1.18871797 1.23186278
 1.36855559 0.61925198 0.22983034 0.03651661 1.02352022 0.14287639
 0.49933415 0.2912582  0.90944555 0.81959766 0.32864536 1.73558196
 0.23184254 1.24717896 0.09769005 0.0970638  2.82502663 0.60577013
 1.84399294 0.13640348 1.21786031 3.25825143 0.81690449 1.05304262
 0.63252113 0.04066502 1.14090509 1.49246806 0.82952048 1.12636766
 0.74762771 0.35360294 1.11457964 0.2164677  1.77447237 0.42208736
 0.47978615 0.02045091 1.76591521 0.18899067 1.23618711 0.05121453
 0.19106188 1.03416012 0.76217869 1.51341675 1.90201763 0.39715556
 1.39424324 1.01614588]


In [27]:
mask2 = data < 0
neg_data = data[mask2]
print(neg_data)

[-0.82601936 -0.02676622 -0.07135342 -1.06410131 -0.44967324 -0.66370834
 -0.92808674 -0.4656751  -2.04216234 -0.51030471 -0.23213848 -1.19793494
 -0.99093971 -1.40460626 -0.76429841 -0.87345069 -0.76289725 -0.20060392
 -1.43057167 -0.19252974 -1.66568792 -0.56720663 -0.59050818 -0.12947179
 -0.35706355 -1.43185427 -0.27907981 -0.41835428 -1.58474714 -0.96438774
 -0.53767643 -0.17402474 -0.39239331 -0.2758249  -1.49836476 -0.1055442
 -0.8229813  -0.13709468 -0.05693036 -0.37361949 -0.40203509 -0.39535995
 -1.15149747 -0.3729756 ]


In [20]:
#remove outlier
print(data [data > 3])

[]


In [21]:
print(data[data < -3])

[-3.2629671]


# Matrix Algebra

In [29]:
# np.linalg for heavy computation
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [30]:
b = np.linalg.inv(a)   #matrix Inverse
print(b)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [33]:
I = a @ b   #matrix Multiplication (identity matrx)
print(I)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [34]:
eig_vals = np.linalg.eigvals(a)
print(eig_vals)

[-0.37228132  5.37228132]


In [35]:
j = a * b
print(j) 

[[-2.   2. ]
 [ 4.5 -2. ]]


In [ ]:
#eigen values