In [2]:
import numpy as np

In [9]:
arr = np.array([1,3,5,7,9])
print (arr)

[1 3 5 7 9]


In [10]:
print(arr.shape)

(5,)


In [11]:
print(arr.ndim)

1


In [12]:
print(arr.dtype)

int64


In [14]:
arr2 = np.array([[1,2],[3,4]])
print(arr2.shape)

(2, 2)


In [15]:
print(arr2.ndim)

2


In [16]:
print(arr2.size)

4


In [18]:
#print(np.dtype(float))

float64


# Zeros and Ones

In [22]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
print(np.ones((2,5,1)))

[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [28]:
print(np.ones((2,5,4)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# Range Methods

In [25]:
num = np.arange(0,10,2)
print(num)

[0 2 4 6 8]


In [32]:
num = np.arange(0,101)
print(num)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [26]:
num1 = np.linspace(0,1,5)
print(num1)

[0.   0.25 0.5  0.75 1.  ]


# Random

In [34]:
arr3 = np.random.rand(3,2)
print(arr3)

[[0.07787674 0.12201551]
 [0.78836703 0.54080349]
 [0.70108446 0.44046284]]


In [35]:
arr4 = np.random.randn(5)
print(arr4)

[ 0.1196264   0.12694483 -1.46803756 -0.21887964  0.25594925]


In [36]:
arr3 = np.random.randn(10)
print(arr3)

[-2.39102868 -0.24611118 -0.61008192  0.50732449  0.45820767 -0.14936943
 -1.03784555  0.6139528  -1.31168351 -1.14890382]


# Slicing

In [37]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [40]:
print(a[1:4:1])

[1 2 3]


In [41]:
print(a[::2])

[0 2 4 6 8]


# 2D Slicing

In [43]:
matrix = np.random.rand(10,10)
print(matrix)

[[0.35970174 0.68909111 0.44789293 0.77309422 0.31602824 0.39187069
  0.11640292 0.2635124  0.57456834 0.59710173]
 [0.3769611  0.62444695 0.42063046 0.16814573 0.58934652 0.88023538
  0.5426216  0.43848834 0.73483177 0.62142792]
 [0.85667945 0.55405296 0.46367971 0.49130018 0.84399006 0.20060787
  0.02631734 0.87890027 0.73076508 0.74200224]
 [0.510408   0.42550529 0.84494507 0.95390258 0.9848037  0.52869678
  0.76938618 0.56080378 0.10774302 0.11351843]
 [0.00291371 0.2515646  0.43577955 0.71213632 0.23442151 0.67747285
  0.31946234 0.57661733 0.73542562 0.26799493]
 [0.92463353 0.9098128  0.15319712 0.45843654 0.41802673 0.70951972
  0.09282239 0.99962895 0.59274901 0.95265534]
 [0.58160717 0.35644037 0.46507432 0.21093021 0.78210136 0.70613309
  0.61097905 0.30044592 0.66274067 0.55981168]
 [0.86915617 0.14338741 0.67593115 0.90453251 0.96852284 0.74553144
  0.79977922 0.36532623 0.08486852 0.27981843]
 [0.94635597 0.46932042 0.07397185 0.09336309 0.98622015 0.02036831
  0.57090092

In [44]:
row_zero = matrix[0:1]
print(row_zero)

[[0.35970174 0.68909111 0.44789293 0.77309422 0.31602824 0.39187069
  0.11640292 0.2635124  0.57456834 0.59710173]]


In [46]:
col_five = matrix[:,5]
print(col_five)

[0.39187069 0.88023538 0.20060787 0.52869678 0.67747285 0.70951972
 0.70613309 0.74553144 0.02036831 0.8485321 ]


In [48]:
top_corner= matrix[0:3]
print(top_corner)

[[0.35970174 0.68909111 0.44789293 0.77309422 0.31602824 0.39187069
  0.11640292 0.2635124  0.57456834 0.59710173]
 [0.3769611  0.62444695 0.42063046 0.16814573 0.58934652 0.88023538
  0.5426216  0.43848834 0.73483177 0.62142792]
 [0.85667945 0.55405296 0.46367971 0.49130018 0.84399006 0.20060787
  0.02631734 0.87890027 0.73076508 0.74200224]]


In [57]:
bottom_corner = matrix[-3:, -3:]
print(bottom_corner)

[[0.36532623 0.08486852 0.27981843]
 [0.5040664  0.12719509 0.81651079]
 [0.1461406  0.74061479 0.97756684]]


In [59]:
bottom_corner = matrix[7:,7:]
print(bottom_corner)

[[0.36532623 0.08486852 0.27981843]
 [0.5040664  0.12719509 0.81651079]
 [0.1461406  0.74061479 0.97756684]]


In [60]:
#first element
a = matrix[0:1,0:1]
print(a)

[[0.35970174]]


In [61]:
print(a.ndim)

2


# Value Retriving

In [62]:
a = matrix[0][1]
print(a)

0.689091107740409


In [63]:
a = matrix[1]
print(a)

[0.3769611  0.62444695 0.42063046 0.16814573 0.58934652 0.88023538
 0.5426216  0.43848834 0.73483177 0.62142792]


In [64]:
a = matrix[1][5]
print(a)

0.8802353845806231


In [67]:
top_corner[0][0] = 5
print(top_corner)

[[5.         0.68909111 0.44789293 0.77309422 0.31602824 0.39187069
  0.11640292 0.2635124  0.57456834 0.59710173]
 [0.3769611  0.62444695 0.42063046 0.16814573 0.58934652 0.88023538
  0.5426216  0.43848834 0.73483177 0.62142792]
 [0.85667945 0.55405296 0.46367971 0.49130018 0.84399006 0.20060787
  0.02631734 0.87890027 0.73076508 0.74200224]]


In [68]:
print(matrix)

[[5.00000000e+00 6.89091108e-01 4.47892928e-01 7.73094215e-01
  3.16028240e-01 3.91870685e-01 1.16402918e-01 2.63512404e-01
  5.74568336e-01 5.97101731e-01]
 [3.76961100e-01 6.24446947e-01 4.20630460e-01 1.68145734e-01
  5.89346519e-01 8.80235385e-01 5.42621600e-01 4.38488342e-01
  7.34831767e-01 6.21427924e-01]
 [8.56679453e-01 5.54052955e-01 4.63679714e-01 4.91300183e-01
  8.43990057e-01 2.00607873e-01 2.63173357e-02 8.78900270e-01
  7.30765082e-01 7.42002239e-01]
 [5.10408002e-01 4.25505292e-01 8.44945065e-01 9.53902575e-01
  9.84803695e-01 5.28696781e-01 7.69386180e-01 5.60803778e-01
  1.07743019e-01 1.13518428e-01]
 [2.91371008e-03 2.51564598e-01 4.35779552e-01 7.12136317e-01
  2.34421512e-01 6.77472849e-01 3.19462341e-01 5.76617327e-01
  7.35425623e-01 2.67994934e-01]
 [9.24633525e-01 9.09812798e-01 1.53197124e-01 4.58436543e-01
  4.18026725e-01 7.09519725e-01 9.28223912e-02 9.99628949e-01
  5.92749013e-01 9.52655344e-01]
 [5.81607170e-01 3.56440373e-01 4.65074323e-01 2.10930213e