In [2]:
import numpy as  np

In [4]:
num1 = np.array([1,2,3,4,5])
num2 = np.array([6,7,8,9,10])
print(num1)

[1 2 3 4 5]


In [5]:
sum = num1 + num2
print(sum)

[ 7  9 11 13 15]


In [6]:
print(num1.mean())

3.0


In [9]:
num2 = [3,9,4,5,8]

In [10]:
print(np.sort(num2))

[3 4 5 8 9]


In [14]:
print(np.sqrt(num2))

[1.73205081 3.         2.         2.23606798 2.82842712]


In [15]:
print(np.exp(num2))

[  20.08553692 8103.08392758   54.59815003  148.4131591  2980.95798704]


In [16]:
print(np.add(num1,num2))

[ 4 11  7  9 13]


# Mathematical Operations

In [18]:
x = np.array([-2,-1,0,1,2])
y = np.array([10,20,30,40,50])
z = np.array([1,2,3,4,5])

In [19]:
print(np.add(x,y,z))

[ 8 19 30 41 52]


In [21]:
print(np.subtract(x,y,z))

[-12 -21 -30 -39 -48]


In [22]:
print(np.multiply(x,y,z))

[-20 -20   0  40 100]


In [45]:
x = np.array([-2,-1,0,1,2])
y = np.array([10,20,30,40,50])
z = np.array([1,2,3,4,5])

In [51]:
print(np.divide(y,z))

[10. 10. 10. 10. 10.]


In [47]:
print(np.power(z,2))

[ 1  4  9 16 25]


In [48]:
print(np.absolute(x))

[2 1 0 1 2]


In [49]:
print(np.negative(x))

[ 2  1  0 -1 -2]


In [50]:
print(np.mod(y,3))

[1 2 0 1 2]


# Trigonometry & Exponential

In [31]:
print(np.sin([0,np.pi/2]))

[0. 1.]


In [32]:
print(np.cos([0,np.pi]))

[ 1. -1.]


In [33]:
print(np.exp(x))

[0.13533528 0.36787944 1.         2.71828183 7.3890561 ]


In [34]:
print(np.log([1,np.e]))

[0. 1.]


In [35]:
print(np.log10([10,100]))

[1. 2.]


In [44]:
z

array([-20, -20,   0,  40, 100])

In [36]:
print(np.sqrt(z))

[        nan         nan  0.          6.32455532 10.        ]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_16388\2942609040.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(z))


# Comparison & Logic

In [53]:
x = np.array([-2,-1,0,1,2])
y = np.array([10,20,30,40,50])
z = np.array([1,2,3,4,5])

In [54]:
print(np.greater(z,3))

[False False False  True  True]


In [55]:
print(np.less(z,3))

[ True  True False False False]


In [40]:
print(np.equal(z,3))

[False False False False False]


In [56]:
print(np.logical_and (z > 2, z < 5))

[False False  True  True False]


In [57]:
print(np.logical_or (z < 2, z > 4))

[ True False False False  True]


In [58]:
print(np.sin(x))

[-0.90929743 -0.84147098  0.          0.84147098  0.90929743]


In [61]:
print (np.logical_not ( z > y, z < x ))

[ True  True  True  True  True]


In [63]:
print(np.cos([1, np.pi]))

[ 0.54030231 -1.        ]


In [64]:
print(np.cos([0, np.pi/2, np.pi, 2*np.pi]))


[ 1.000000e+00  6.123234e-17 -1.000000e+00  1.000000e+00]
